### ISSUE TITLE
Pushing image to desi registry times out when proxy is used

### ISSUE THREAD

**Issue by jolly2** [deis/registry#61]
In /etc/default/docker , 

export HTTP_PROXY="corp proxy"
export NO_PROXY="deis-router-service-ip-address:80"

If HTTP_PROXY is not used, then, deis cannot pull the image from outside (docker hub)
If HTTP_PROXY is used, then, git push fails to push the image to the deis-registry (times out)
So added NO_PROXY for the deis-router-ip-address:80 . Still it is not able to push the image to deis-registry. 
If HTTP_PROXY is removed, then, git push successfully pushes it to deis registry. But, should have the image ready by pulling it  with HTTP_PROXY on. 

How to enable both?

Thanks

**Comment by kmala** [comment]
since the registry is internal it doesn't go through the router, it directly calls the registry service so you should set the NO_PROXY to "deis-registry-service-ip-address:80" if you are on v2.1 or before.
From the next release v2.2 which we will be releasing next week you should be able to just specify `localhost` as we drop a service on each node to proxy the requests

**Comment by jolly2** [comment]
Hello,I have tried with NO_PROXY=deis-service-registry-ip-address:80. I always get this error. Not sure why it is trying to deploy to "localhost", instead of registry service address. This deis code is a week old code from github. Below is the log from deis-builder-instance2-
2016-07-13T15:52:49.858369201Z Traceback (most recent call last):2016-07-13T15:52:49.858458544Z   File "/deploy.py", line 120, in <module>2016-07-13T15:52:49.858325930Z Step 1 : FROM 192.168.3.8:80/httpd:2.42016-07-13T15:52:49.858522365Z ---> d4ba297db48a2016-07-13T15:52:49.858531586Z Step 2 : COPY ./resolv.conf /etc/resolv.conf2016-07-13T15:52:49.858538559Z ---> Using cache2016-07-13T15:52:49.858545318Z ---> 8c32fba3f8ca2016-07-13T15:52:49.858553293Z Step 3 : COPY ./public-html/ /usr/local/apache2/htdocs/2016-07-13T15:52:49.858560356Z ---> Using cache2016-07-13T15:52:49.858567025Z ---> cee3071217da2016-07-13T15:52:49.858573774Z Successfully built cee3071217da2016-07-13T15:52:49.858580492Z Pushing to registry2016-07-13T15:52:49.858599704Z     log_output(stream, False)2016-07-13T15:52:49.858639743Z   File "/deploy.py", line 20, in log_output2016-07-13T15:52:49.858663361Z     for chunk in stream:2016-07-13T15:52:49.858678603Z   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 217, in _stream_helper2016-07-13T15:52:49.870833599Z     data = reader.read(1)2016-07-13T15:52:49.870899076Z   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 320, in read2016-07-13T15:52:49.882279299Z     flush_decoder = True2016-07-13T15:52:49.882384830Z   File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__2016-07-13T15:52:49.901813750Z     self.gen.throw(type, value, traceback)2016-07-13T15:52:49.901897186Z   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 233, in _error_catcher2016-07-13T15:52:49.901909829Z     raise ReadTimeoutError(self._pool, None, 'Read timed out.')2016-07-13T15:52:49.901917690Z requests.packages.urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.Thanks!

**Comment by kmala** [comment]
what is your docker version....this looks like similar to https://github.com/deis/registry/issues/60

**Comment by jolly2** [comment]
Yes it is a similar problem . However, i see this problem when http_proxy and no_proxy are used together. If both are removed, deploy works fine. I would have to pull the images that i need from outside with http_proxy and then remove http_proxy to tag and push it to deis registry.
Docker version 1.11.2, build b9f10c9
Thanks

**Comment by jolly2** [comment]
Downgraded docker 1.10.3.  It is a different problem with deis-registry now. Still cannot use http_proxy and no_proxy settings together in docker daemon. I downloaded the images to a private repo on another machine and pulled and pushed into deis registry. Push seemed successful.  But, system became slow. gunicorn has hogged more than 100% of CPU for about 20 mins now. Deis is using all the 12 core cpu. Is there any config that I can tweak in to bypass this problem?

**Comment by kmala** [comment]
@jolly2 can you tell which process is hogging the cpu and get the logs of the corresponding deis component

**Comment by jolly2** [comment]
ps -ef | grep 7494
106       7494  7372 55 08:53 ?        00:32:24 /usr/bin/python /usr/local/bin/gunicorn -c /app/deis/gunicorn/config.py api.wsgi

PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  7494 106       20   0  171272  47600  11296 R  99.6  0.2  33:59.03 gunicorn

System is extremely so to capture the logs..I will try. But, I had to hard boot the cluster everytime..
Thanks

**Comment by bacongobbler** [comment]
@jolly2 just read through this issue. The reason the controller is deploying to localhost is because it is hitting the [registry proxy](https://github.com/deis/registry-proxy). This is normal, and your proxy settings should reflect that.

As for the 12 core CPU issue, this has been resolved. There were known memory/CPU hogging issues in earlier versions of v2 that have long since been resolved. You should have a better experience if you're using v2.8.0.

If you have the time please feel free to try again on v2.8.0, but otherwise I'm going to close this as resolved unless someone else pipes up about proxy issues. Thanks!
