### ISSUE TITLE
Error when pushing docker image to registry 

### ISSUE THREAD

**Issue by Akshaykapoor** [deis/registry#81]
I'm running Workflow v2.10 with a manual patch to use `127.0.0.1` instead of `localhost` for `DEIS_REGISTRY_SERVICE_HOST` as mentioned https://github.com/deis/workflow/issues/678 . Everything was working well until today morning i've started to see failures whenever i try to push to an existing branch or create a new app. This is the error that i get when doing the `git push`

```
Pushing to registry
{'status': 'The push refers to a repository [127.0.0.1:5555/web-test]'}

remote: 2017/02/16 07:23:21 Error running git receive hook [The controller returned an error when publishing the release: Unknown Error (400): {"detail":"Error while pulling image: Get http://127.0.0.1:5555/v1/repositories/web-test/images: dial tcp 127.0.0.1:5555: getsockopt: connection refused"}]
...
...
size of streamed logs 3918
Waiting for the deis/dockerbuild-web-test-9067a9d2-a0da63ab pod to end. Checking every 100ms for 15m0s
Done
Checking for builder pod exit code
Done
Build complete.
Launching App...
remote: 2017/02/16 07:23:21 Error running git receive hook [The controller returned an error when publishing the release: Unknown Error (400): {"detail":"Error while pulling image: Get http://127.0.0.1:5555/v1/repositories/web-test/images: dial tcp 127.0.0.1:5555: getsockopt: connection refused"}]
```

From the controller logs, 

```
ERROR:root:Error while pulling image: Get http://127.0.0.1:5555/v1/repositories/iconic-nonesuch/images: dial tcp 127.0.0.1:5555: getsockopt: connection refused
Traceback (most recent call last):
  File "/app/api/models/release.py", line 171, in get_port
    port = docker_get_port(self.image, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 199, in get_port
    return DockerClient().get_port(target, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 76, in get_port
    info = self.inspect_image(target)
  File "/usr/local/lib/python3.5/dist-packages/backoff.py", line 286, in retry
    ret = target(*args, **kwargs)
  File "/app/registry/dockerclient.py", line 152, in inspect_image
    self.pull(repo, tag=tag)
  File "/usr/local/lib/python3.5/dist-packages/backoff.py", line 286, in retry
    ret = target(*args, **kwargs)
  File "/app/registry/dockerclient.py", line 124, in pull
    log_output(stream, 'pull', repo, tag)
  File "/app/registry/dockerclient.py", line 174, in log_output
    stream_error(chunk, operation, repo, tag)
  File "/app/registry/dockerclient.py", line 191, in stream_error
    raise RegistryException(message)
registry.dockerclient.RegistryException: Error while pulling image: Get http://127.0.0.1:5555/v1/repositories/iconic-nonesuch/images: dial tcp 127.0.0.1:5555: getsockopt: connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/build.py", line 65, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 461, in deploy
    deploys[scale_type] = self._gather_app_settings(release, app_settings, scale_type, replicas)  # noqa
  File "/app/api/models/app.py", line 1012, in _gather_app_settings
    envs = self._build_env_vars(release)
  File "/app/api/models/app.py", line 823, in _build_env_vars
    port = release.get_port()
  File "/app/api/models/release.py", line 179, in get_port
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Error while pulling image: Get http://127.0.0.1:5555/v1/repositories/iconic-nonesuch/images: dial tcp 127.0.0.1:5555: getsockopt: connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 527, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 533, in post_save
    build.create(self.user)
  File "/app/api/models/build.py", line 79, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Error while pulling image: Get http://127.0.0.1:5555/v1/repositories/iconic-nonesuch/images: dial tcp 127.0.0.1:5555: getsockopt: connection refused
100.96.2.74 "POST /v2/hooks/build/ HTTP/1.1" 400 161 "deis-builder"

```

registry-proxy

```
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3Ac5e8f860bff8a7b6c71dd992051b0074eef1f35a1ec0eb85b89e6fad6f75a2 HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3A37793e76b80da9bf64d0b9cda6113ed7d6752f70a18aaca4fb334d95b0d5b2 HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3Aebae89df1b24062237090db83234fa5198bf0ec95966bcd0114e8458a3b87a HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3A861a733d47aa6f4a281eddcaab5dedadc23e02acdcaa77d625f7d6e9ff80 HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3Acd8a70303abf53dbc18d23bbf4d3f7940954c5fdea080f21633bebf3d709be HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "HEAD /v2/iconic-nonesuch/blobs/sha256:c5e8f860bff8a7b6cbb71d92051b0074eef1f35a1ec0eb85b89e6fad6f75a2 HTTP/1.1" 307 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "HEAD /v2/iconic-nonesuch/blobs/sha256:861a733d45ce57aa6f481eddcaab5dedadc23e02acdcaa77d625f7d6e9ff80 HTTP/1.1" 307 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "HEAD /v2/iconic-nonesuch/blobs/sha256:cd8a70303abf53dbc18d2823bbf4d3f7940954c5fdea080f21633bebf3d709be HTTP/1.1" 307 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "HEAD /v2/iconic-nonesuch/blobs/sha256:37793e76b80da9f1b4d0b9cda6113ed7d6752f70a18aaca4fb334d95b0d5b2 HTTP/1.1" 307 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "HEAD /v2/iconic-nonesuch/blobs/sha256:ebae89df1b240c5237090db83234fa5198bf0ec95966bcd0114e8458a3b87a HTTP/1.1" 307 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3A8cadbcc591c5434732b1369570e26b500dd0629a1da2c470522c649c934d82 HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "HEAD /v2/iconic-nonesuch/blobs/sha256:8cadbcc591c54347a4b1369570e26b500dd0629a1da2c470522c649c934d82 HTTP/1.1" 307 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3A56c6ccbe0d684ac67104433b51a0ee9ecde2866d6e0a3878f4391a9de72904 HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "HEAD /v2/iconic-nonesuch/blobs/sha256:56c6ccbe0d68fd467104433b51a0ee9ecde2866d6e0a3878f4391a9de72904 HTTP/1.1" 307 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3A1496391d955720aaf94deb694968ea0d4ffb5463417c126e50ce0942fb46e5 HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "HEAD /v2/iconic-nonesuch/blobs/sha256:1496391d9d1720aaf94deb694968ea0d4ffb5463417c126e50ce0942fb46e5 HTTP/1.1" 307 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3A1ddfaaf1b6a67e1384b5ea8db83c32fffb9cb38ba1663840c633a24e33443c32 HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3A33d67d70afeacb1f44361dc61d94cf38a7ee5167a030c88d6906cf76611455 HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=klutzy-dragster&mount=sha256%3A9c1bc3c371bbb5ffb75b052221ce88a1c89f78187e7a2596c2d3fdd5f2043a HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=frozen-asteroid&mount=sha256%3A76610e0bf5892e24cebd4153c7668284aa1d1151b7c3b0c7d50c579aa5ce75 HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"
100.96.1.1 - - [16/Feb/2017:07:43:17 +0000] "POST /v2/iconic-nonesuch/blobs/uploads/?from=frozen-asteroid&mount=sha256%3Afce58aad85a763fe3c419db16885eb6f7a670a42824ea618414b8fb309ccde HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.26-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" "-"

```

If https://github.com/deis/registry/issues/64 had to be the issue, then it shouldn't even have started for the very first time i believe, but i've started facing this issue since today only after running it successfully for more than a week. 

Any guidance in the right direction can be helpful to debug this.

**Comment by Akshaykapoor** [comment]
I figured it out. The issue was `deis-registry-proxy` was not running on one of the nodes. Had to restart the `kubelet` service and things started to work fine after that.
